# .goreleaser.yaml

project_name: cargo-docs

version: 2

builds:
  - id: cargo-docs
    binary: cargo-docs
    builder: rust
    tool: cargo
    command: zigbuild
    targets:
      - aarch64-unknown-linux-musl
      - x86_64-unknown-linux-musl
      - x86_64-pc-windows-gnu
  - id: cargo-book
    binary: cargo-book
    builder: rust
    tool: cargo
    command: zigbuild
    targets:
      - aarch64-unknown-linux-musl
      - x86_64-unknown-linux-musl
      - x86_64-pc-windows-gnu

archives:
  - id: archive
    builds:
      - cargo-docs
      - cargo-book
    files:
      - LICENSE
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ .Target }}
    format_overrides:
      - goos: windows
        format: zip
