# .goreleaser.yaml

project_name: cargo-docs

version: 2

builds:
  - id: main
    builder: rust
    tool: cargo
    command: zigbuild
    targets:
      - x86_64-apple-darwin

archives:
  - id: archive
    builds:
      - main
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
