# .goreleaser.yaml

project_name: cargo-docs

version: 2

builds:
  - id: main
    builder: rust
    tool: cargo
    command: zigbuild
    targets:
      - aarch64-unknown-linux-musl
      - x86_64-unknown-linux-musl
      - x86_64-pc-windows-gnu

archives:
  - id: archive
    builds:
      - main
    files:
      - LICENSE
    name_template: {{ .ProjectName }}-{{ .Target }}
    format_overrides:
      - goos: windows
        format: zip
