name: goreleaser

on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  snapshot:
    if: startsWith(github.ref, 'refs/tags/') != true
    runs-on: ubuntu-latest
    container:
      image: btwiuse/arch:rust-goreleaser

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: btwiuse/arch:rust-goreleaser

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
